### ISSUE TITLE
Frequency - ATTiny85

### ISSUE THREAD

**Issue by classic-audio** [micooke/PWM#2]
**I am using this library for ATTiny85.**
The frequency I want to use is 100Hz (for gramophone speed test).
The problem:

I use these lines to set the frequency: 
	pwm.set(0, 'b', 793, 4);
        pwm.start(0); 

The expected settings is:
	pwm.set(0, 'b', 100, 4);
        pwm.start(0); 
(this setup -> the frequency is 15Hz

Is there anything I can do to correct this?

**Comment by micooke** [comment]
Hey there 👋 
I don't think I've tested it down that low, but I'll try to find one of my attiny85 and test it this week. 
I haven't looked at this code in ages, but my first thought is maybe it's a register setting conflict from Arduino as that uses timer 0 for ```millis()``` etc, so I would first try using timer 1 as it uses the same pin on the 85.
```pwm.set(1, 'a', 100, 4);```

**Comment by classic-audio** [comment]
Hi,
I tried 
pwm.set(1, 'a', 100, 4);
and this was also was 15Hz pwm signal

Using the library with Uno - no problem everything works - frequency 100Hz was correct.

Could there be a point of ATTiny85 osc. frequency (1MHz <-> 8 MHz)  ?

**Comment by classic-audio** [comment]
Hi again,
I have now "burned" ATTiny85 to 8MHz.
and the problem is solved.
That was the reason. Perhaps a small note could help others.

But with such a low frequency it mignt be preferred to go with 1 MHZ and getting a little easier calibration.

**Comment by micooke** [comment]
One question, with the ATTiny85 running at 1MHz if you print off ```F_CPU``` is this the correct value (1,000,000)?
I suspect this isn't being set properly in ```boards.txt``` as everything is based off this value.
Happy to make a note, but I would like to fix it for you too 😁

**Comment by classic-audio** [comment]
I am not shure how to check  boards.txt.
Please explain a bit more?


**Here is the complete code I am using**
`// --- Ref:  https://github.com/micooke/PWM ---
#include <util/atomic.h>
#include <PWM.h>
void setup(){
	pwm.set(0, 'b', 100, 4);
  pwm.start(0); 
}
void loop(){}`

**Comment by micooke** [comment]
The ```boards.txt``` should be in your Arduino folder, where it stores your projects. Probably the best question is what third party BSP are you using/what is the source you used. Previously I have used ```https://raw.githubusercontent.com/damellis/attiny/ide-1.6.x-boards-manager/package_damellis_attiny_index.json```. If you tell me this I'll be able to chase it down and check that the fuse settings and f_cpu are correct for 1MHz.

**Comment by classic-audio** [comment]
I have now downloaded the suggested package from damellis.
And used burn bootloader to set for 1MHz.
After that I loaded again the small code (see above) and now the frequency is correct:   100Hz @ 1MHz / ATTiny85

**Comment by classic-audio** [comment]
That is a bit difficult to find, but here is my finding:
SpenceKonde  ATTinyCore (not the latest version, mine is perhaps 1 year old

**Comment by micooke** [comment]
I just had a look at that core, which looks very very thorough. Fantastic work has been done on it, lots of work to include software serial libraries and modifying a bunch of other libraries to work on the attiny. But in this case it looks like the fuze settings for 1MHz don't match the ```f_cpu``` value.

**Comment by micooke** [comment]
If you are happy, I'm going to close this as this was a BSP issue 😁

**Comment by classic-audio** [comment]
Hi Mark,

Yes, I have a solution.

Thank you very much.
